// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiS0ga8SKPdQLCQzxzFRuUJgJEBKILbFs',
    appId: '1:284885568525:web:0634dff1c66e1e6c815944',
    messagingSenderId: '284885568525',
    projectId: 'hub-de-ideias',
    authDomain: 'hub-de-ideias.firebaseapp.com',
    storageBucket: 'hub-de-ideias.appspot.com',
    measurementId: 'G-TG8L4N483J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWZK4ii6gmhbI_HAgcuaUrwrx0TjZJEWw',
    appId: '1:284885568525:android:3ab4db9a82724742815944',
    messagingSenderId: '284885568525',
    projectId: 'hub-de-ideias',
    storageBucket: 'hub-de-ideias.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5iLk4FAg4flZSTrbUWqYT3hCKpe05TdI',
    appId: '1:284885568525:ios:26603164d7b2f9cf815944',
    messagingSenderId: '284885568525',
    projectId: 'hub-de-ideias',
    storageBucket: 'hub-de-ideias.appspot.com',
    iosClientId: '284885568525-7fgualtab386riii64i7v9d93daflnd5.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterHubIdeias',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5iLk4FAg4flZSTrbUWqYT3hCKpe05TdI',
    appId: '1:284885568525:ios:26603164d7b2f9cf815944',
    messagingSenderId: '284885568525',
    projectId: 'hub-de-ideias',
    storageBucket: 'hub-de-ideias.appspot.com',
    iosClientId: '284885568525-7fgualtab386riii64i7v9d93daflnd5.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterHubIdeias',
  );
}
